"""add role

Revision ID: 3e3ef5ddd7c8
Revises: 121348261087
Create Date: 2026-05-08 08:05:38.264522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3e3ef5ddd7c8'
down_revision: Union[str, Sequence[str], None] = '121348261087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = postgresql.ENUM('USER', 'ADMIN', name='role')
    role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'users',
        sa.Column(
            'role',
            role_enum,
            nullable=False,
            server_default='USER',
        ),
    )

    op.alter_column('users', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    role_enum = postgresql.ENUM('USER', 'ADMIN', name='role')
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
