"""add relationship between tables

Revision ID: 7c569ca9f054
Revises: ea124cc5ea99
Create Date: 2026-04-30 19:24:29.262546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7c569ca9f054"
down_revision: Union[str, Sequence[str], None] = "ea124cc5ea99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "contacts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("users", sa.Column("username", sa.String(length=30), nullable=False))
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    op.add_column("users", sa.Column("avatar", sa.String(), nullable=True))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "avatar")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "username")
    op.drop_constraint(None, "contacts", type_="foreignkey")
    op.drop_column("contacts", "user_id")
    # ### end Alembic commands ###
