from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from src.schemas.user import UserCreate
from src.models.user import User


class UserRepository:
    def __init__(self, db_session: AsyncSession):
        """
        Initializes the UserRepository with a database session.

        args:
            db_session (AsyncSession): An Asynchronous object to connect to the database.
        """
        self.db_session = db_session

    async def get_user_by_email(self, email: str) -> User | None:
        """
        Get a user by their email address.

        args:
            email (str): The email address of the user to retrieve.

        returns:
            User: The user object if found, otherwise None.
        """

        stmt = select(User).filter(User.email == email)
        result = await self.db_session.execute(stmt)
        if result is None:
            raise Exception(f"Failed to execute query for email: {email}")
        return result.scalars().first()

    async def create_user(
        self, body: UserCreate, hashed_password: str, avatar: str
    ) -> User:
        """
        Create a new user in the database.

        args:
            body (UserCreate): The user data to create.
            hashed_password (str): The hashed password for the user.
            avatar (str): The avatar URL for the user. Auto-generated by Gravatar based on the user's email.

        returns:
            User: The newly created user object.
        """
        new_user = User(
            **body.model_dump(exclude_unset=True, exclude={"password"}),
            hashed_password=hashed_password,
            avatar=avatar,
        )

        self.db_session.add(new_user)
        await self.db_session.commit()
        await self.db_session.refresh(new_user)
        return new_user

    async def confirmed_email(self, email: str) -> None:
        """Confirm a user's email address.

        args:
            email (str): The email address of the user to confirm.

        returns:
                None: This method does not return anything. It updates the user's confirmed status in the database.
        """
        user = await self.get_user_by_email(email)
        if not user:
            return None
        user.confirmed = True
        await self.db_session.commit()

    async def update_avatar_url(self, email: str, url: str) -> User:
        """Update a user's avatar URL.

        args:
            email (str): The email address of the user to update.
            url (str): The new avatar URL for the user.

        returns:
            User: The updated user object.
        """
        user = await self.get_user_by_email(email)
        user.avatar = url
        await self.db_session.commit()
        await self.db_session.refresh(user)
        return user

    async def update_password(self, email: str, hashed_password: str) -> User | None:
        """Update a user's password.

        args:
            email (str): The email address of the user to update.
            hashed_password (str): The new hashed password for the user.

        returns:
            User: The updated user object if the user exists, otherwise None.
        """
        user = await self.get_user_by_email(email)
        if not user:
            return None
        user.hashed_password = hashed_password
        await self.db_session.commit()
        await self.db_session.refresh(user)
        return user
